ITEMS = [
    ("Minerals & Fossils", "Dinosaur Fossil"),
    ("Minerals & Fossils", "Blue Calcite"),
    ("Minerals & Fossils", "Honey Calcite"),
    ("Minerals & Fossils", "Labradorite"),
    ("Minerals & Fossils", "Spectralite"),
    ("Minerals & Fossils", "Red Ammonite"),
    ("Minerals & Fossils", "Purple Agate"),
    ("Minerals & Fossils", "Hourglass Selenite"),
    ("Minerals & Fossils", "Desert Rose Crystal"),
    ("Minerals & Fossils", "Wulfenite Crystal"),
    ("Shells & Marine", "Yellow Dog Conch Shell"),
    ("Shells & Marine", "Butter Clam Shell"),
    ("Shells & Marine", "Brooch Clamshell"),
    ("Shells & Marine", "Conch Shell Eggs"),
    ("Shells & Marine", "Horseshoe Crab"),
    ("Shells & Marine", "Shark Jaw"),
    ("Plant Materials", "Sugar Pinecones"),
    ("Plant Materials", "Pine Cones"),
    ("Plant Materials", "Bottle Tree Seed Pods"),
    ("Plant Materials", "Moss"),
    ("Plant Materials", "Okra Seed Pods"),
    ("Plant Materials", "Driftwood"),
    ("Preserved Specimens", "Duckling"),
    ("Preserved Specimens", "Mummified Duckling"),
    ("Preserved Specimens", "Chipmunk"),
    ("Preserved Specimens", "Opossum"),
    ("Preserved Specimens", "Chameleon"),
    ("Preserved Specimens", "Snakeskin"),
    ("Preserved Specimens", "Chick"),
    ("Preserved Specimens", "Weasel"),
    ("Preserved Specimens", "Fox Head"),
    ("Preserved Specimens", "Chinese Water Dragon"),
    ("Animal Parts", "Fox Tails"),
    ("Animal Parts", "Macaw Feathers"),
    ("Animal Parts", "Goose Feathers"),
    ("Animal Parts", "Turtle Shell"),
    ("Animal Parts", "Bird's Nest"),
    ("Animal Parts", "Wasp Nest"),
    ("Animal Parts", "Cobra Skin"),
    ("Animal Parts", "Butterfly And Moth Wings"),
    ("Animal Parts", "Snake Shed"),
    ("Animal Parts", "Beaver Paw"),
    ("Animal Parts", "Rabbit Pelt"),
    ("Animal Parts", "Coyote Tail"),
    ("Animal Parts", "Raccoon Pelt"),
    ("Animal Parts", "Bobcat Hyde"),
    ("Animal Parts", "Raccoon Tail"),
    ("Animal Parts", "Silver Fox Hide"),
    ("Animal Parts", "Faun Hide"),
    ("Animal Parts", "Woodboring Jewel Beatles"),
    ("Bones & Skulls", "Giraffe Vertebrae"),
    ("Bones & Skulls", "Beaver Skull"),
    ("Bones & Skulls", "Beaver Jaw"),
    ("Bones & Skulls", "Fox Skull"),
    ("Bones & Skulls", "Hip Bone"),
    ("Bones & Skulls", "Raccoon Skull"),
    ("Bones & Skulls", "Deer Jaw"),
    ("Bones & Skulls", "Deer Bones"),
    ("Bones & Skulls", "Deer Antler"),
    ("Bones & Skulls", "Fishbone Tail"),
    ("Bones & Skulls", "Burmese Python Vertebrae"),
    ("Bones & Skulls", "Moose Tooth"),
    ("Resin Replicas", "Madagascar Hissing Cockroach"),
    ("Resin Replicas", "Beaver Teeth"),
    ("Resin Replicas", "Beaver Paw"),
    ("Resin Replicas", "Iguana Head"),
    ("Resin Replicas", "Iguana Foot"),
    ("Miscellaneous", "Arrowheads"),
    ("Miscellaneous", "Clay Bowl"),
]
